// GENERATED by scripts/generate-languages.mjs — do not edit by hand.
// Regenerate with: npm run generate:languages

import type { LanguageMap } from './types'

export const languages: LanguageMap = {
  "javascript": {
    "projects": [
      "webnog",
      "pi",
      "config",
      "piet",
      "rend",
      "svgink",
      "glitzi",
      "wowdnd",
      "octometrist"
    ],
    "startYear": 2008,
    "endYear": 2026
  },
  "groovy": {
    "projects": [
      "webn",
      "pi",
      "migrations",
      "parrot"
    ],
    "startYear": 2012,
    "endYear": 2026
  },
  "java": {
    "projects": [
      "webn-proxy",
      "oldpi"
    ],
    "startYear": 2012,
    "endYear": 2026
  },
  "c#": {
    "projects": [],
    "startYear": null,
    "endYear": null
  },
  "go": {
    "projects": [
      "config",
      "sched",
      "excre",
      "clinton",
      "helja"
    ],
    "startYear": 2018,
    "endYear": 2026
  },
  "lua": {
    "projects": [],
    "startYear": null,
    "endYear": null
  },
  "terraform": {
    "projects": [
      "octometrist",
      "rancher"
    ],
    "startYear": 2020,
    "endYear": 2026
  },
  "sql": {
    "projects": [
      "webn",
      "rancher",
      "pi",
      "sched"
    ],
    "startYear": 2009,
    "endYear": 2026
  },
  "python": {
    "projects": [
      "et",
      "portsel",
      "pirana",
      "rancher",
      "zenpull",
      "octometrist",
      "pita"
    ],
    "startYear": 2012,
    "endYear": 2026
  },
  "shell": {
    "projects": [
      "deploy",
      "deploy",
      "scripts",
      "builders",
      "hooks"
    ],
    "startYear": 2012,
    "endYear": 2026
  }
}
