// GENERATED by scripts/generate-languages.mjs — do not edit by hand.
// Regenerate with: npm run generate:languages

import type { LanguageMap } from './types'

export const languages: LanguageMap = {
  "javascript": {
    "projects": [
      "webnog",
      "pi",
      "config",
      "piet",
      "rend",
      "svgink",
      "glitzi",
      "wowdnd",
      "octometrist",
      "auto-ng-crud",
      "black-cats-herbs-and-brews",
      "brew-shrew",
      "brew-shrew-server",
      "cross-stitch",
      "crowdj",
      "detouring.show",
      "dosaki.net",
      "glizi",
      "hell-inc",
      "lockpick",
      "not13",
      "pi_embed_example",
      "portrait-generator",
      "preview-e-r-d",
      "rainbow-trotters",
      "retro-speech-maker",
      "screeps-init",
      "seating-planner",
      "shortener",
      "swords-and-quills",
      "t2erd",
      "t2erd-png",
      "the-analyser",
      "W-screen-world-example",
      "webcomicat-engine"
    ],
    "startYear": 2008,
    "endYear": 2026
  },
  "groovy": {
    "projects": [
      "webn",
      "pi",
      "migrations",
      "parrot",
      "auto-ng-crud",
      "christmastodon",
      "groovy_script_import_test",
      "webcomicat-engine"
    ],
    "startYear": 2012,
    "endYear": 2026
  },
  "java": {
    "projects": [
      "webn-proxy",
      "oldpi",
      "codename-strain",
      "shortener"
    ],
    "startYear": 2012,
    "endYear": 2026
  },
  "c#": {
    "projects": [
      "codename-strain"
    ],
    "startYear": 2015,
    "endYear": 2015
  },
  "go": {
    "projects": [
      "config",
      "sched",
      "excre",
      "clinton",
      "helja",
      "claude-sessions",
      "emote-combat-server",
      "gorm-revel-issue",
      "sqlow"
    ],
    "startYear": 2017,
    "endYear": 2026
  },
  "lua": {
    "projects": [
      "EmoteCombatAddon"
    ],
    "startYear": 2018,
    "endYear": 2018
  },
  "terraform": {
    "projects": [
      "octometrist",
      "rancher"
    ],
    "startYear": 2020,
    "endYear": 2026
  },
  "sql": {
    "projects": [
      "webn",
      "rancher",
      "pi",
      "sched"
    ],
    "startYear": 2009,
    "endYear": 2026
  },
  "python": {
    "projects": [
      "et",
      "portsel",
      "pirana",
      "rancher",
      "zenpull",
      "octometrist",
      "pita",
      "annoyer",
      "codename-strain",
      "diff_humaniser",
      "lockpick",
      "subreddit_header_countdown",
      "warzone-map-buddy"
    ],
    "startYear": 2012,
    "endYear": 2026
  },
  "shell": {
    "projects": [
      "deploy",
      "deploy",
      "scripts",
      "builders",
      "hooks",
      "black-cats-herbs-and-brews",
      "christmastodon",
      "claude-sessions",
      "cross-stitch",
      "crowdj",
      "emote-combat-server",
      "glizi",
      "hell-inc",
      "lockpick",
      "not13",
      "portrait-generator",
      "rainbow-trotters",
      "retro-speech-maker",
      "screeps-init",
      "seating-planner",
      "shortener",
      "sqlow",
      "strange-homeworlds",
      "swords-and-quills",
      "the-analyser",
      "webcomicat-engine"
    ],
    "startYear": 2012,
    "endYear": 2026
  }
}
