/**
 * The gear-and-compass mark. Fills with `currentColor`, which yields all three
 * brand-board variants from one component: gold on navy (primary), navy (solid),
 * and navy on a parchment disc (reverse).
 *
 * Path data is generated by scripts/generate-mark.mjs — adjust the parameters
 * there and re-run rather than editing these strings by hand.
 */
const GEAR =
  'M 40.16 13.29 L 41.22 4.85 L 58.78 4.85 L 59.84 13.29 A 38 38 0 0 1 69.00 17.09 L 75.72 11.86 L 88.14 24.28 L 82.91 31.00 A 38 38 0 0 1 86.71 40.16 L 95.15 41.22 L 95.15 58.78 L 86.71 59.84 A 38 38 0 0 1 82.91 69.00 L 88.14 75.72 L 75.72 88.14 L 69.00 82.91 A 38 38 0 0 1 59.84 86.71 L 58.78 95.15 L 41.22 95.15 L 40.16 86.71 A 38 38 0 0 1 31.00 82.91 L 24.28 88.14 L 11.86 75.72 L 17.09 69.00 A 38 38 0 0 1 13.29 59.84 L 4.85 58.78 L 4.85 41.22 L 13.29 40.16 A 38 38 0 0 1 17.09 31.00 L 11.86 24.28 L 24.28 11.86 L 31.00 17.09 A 38 38 0 0 1 40.16 13.29 Z M 22 50 A 28 28 0 1 0 78 50 A 28 28 0 1 0 22 50 Z'

const NEEDLE = 'M 63 4 L 54.82 45.92 L 34 96 L 45.66 43.04 Z'

interface MarkProps {
  /** Rendered size in pixels. Defaults to 1em so it can sit inline. */
  size?: number
  /** When present the mark is exposed to assistive tech with this label. */
  title?: string
  className?: string
}

export function Mark({ size, title, className }: MarkProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 100 100"
      width={size ?? '1em'}
      height={size ?? '1em'}
      fill="currentColor"
      role={title ? 'img' : undefined}
      aria-hidden={title ? undefined : true}
    >
      {title ? <title>{title}</title> : null}
      <path fillRule="evenodd" d={GEAR} />
      <circle cx="50" cy="50" r="19" fill="none" stroke="currentColor" strokeWidth="3" />
      <path d={NEEDLE} />
    </svg>
  )
}
