import { GEAR, NEEDLE, INNER_R, INNER_W } from './mark-paths.generated'

/**
 * The gear-and-compass mark. Fills with `currentColor`, which yields all three
 * brand-board variants from one component: gold on navy (primary), navy (solid),
 * and navy on a parchment disc (reverse).
 *
 * Path data is generated by scripts/generate-mark.mjs into mark-paths.generated.ts
 * — adjust the parameters there and re-run rather than editing these strings by hand.
 */
interface MarkProps {
  /** Rendered size in pixels. Defaults to 1em so it can sit inline. */
  size?: number
  /** When present the mark is exposed to assistive tech with this label. */
  title?: string
  className?: string
}

export function Mark({ size, title, className }: MarkProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 100 100"
      width={size ?? '1em'}
      height={size ?? '1em'}
      fill="currentColor"
      role={title ? 'img' : undefined}
      aria-hidden={title ? undefined : true}
    >
      {title ? <title>{title}</title> : null}
      <path fillRule="evenodd" d={GEAR} />
      <circle cx="50" cy="50" r={INNER_R} fill="none" stroke="currentColor" strokeWidth={INNER_W} />
      <path d={NEEDLE} />
    </svg>
  )
}
