// Generates src/components/mark-paths.generated.ts — the single source of
// truth for the gear-and-compass path data consumed by src/components/Mark.tsx
// and public/favicon.svg. Adjust the parameters below and re-run rather than
// editing the generated module, Mark.tsx, or favicon.svg by hand.
//   node scripts/generate-mark.mjs

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const C = 50
const TEETH = 8
const R_TIP = 46        // tooth tip radius
const R_ROOT = 38       // valley radius
const R_BAND = 28       // inner edge of the gear ring
const TIP_DEG = 22      // angular width of a tooth at its tip
const ROOT_DEG = 30     // angular width at its base
const NEEDLE_PARAMS = { top: [63, 4], bottom: [34, 96], halfWidth: 4.8, shoulder: 0.56 }
const INNER_R = 19      // inner ring radius
const INNER_W = 3       // inner ring stroke width

const pt = (r, deg) => {
  const a = ((deg - 90) * Math.PI) / 180
  return [C + r * Math.cos(a), C + r * Math.sin(a)]
}
const f = ([x, y]) => `${x.toFixed(2)} ${y.toFixed(2)}`

function gear() {
  const step = 360 / TEETH
  const d = []
  for (let i = 0; i < TEETH; i++) {
    const c = i * step
    // Each tooth's root-start point is already where the previous tooth's
    // closing arc ended, so only the very first tooth needs an explicit
    // move/line into it — anything later would be a zero-length segment.
    if (i === 0) {
      d.push(`M ${f(pt(R_ROOT, c - ROOT_DEG / 2))}`)
    }
    d.push(`L ${f(pt(R_TIP, c - TIP_DEG / 2))}`)
    d.push(`L ${f(pt(R_TIP, c + TIP_DEG / 2))}`)
    d.push(`L ${f(pt(R_ROOT, c + ROOT_DEG / 2))}`)
    d.push(`A ${R_ROOT} ${R_ROOT} 0 0 1 ${f(pt(R_ROOT, (i + 1) * step - ROOT_DEG / 2))}`)
  }
  d.push('Z')
  // Counter-wound hole, cut by fill-rule="evenodd".
  d.push(`M ${C - R_BAND} ${C}`)
  d.push(`A ${R_BAND} ${R_BAND} 0 1 0 ${C + R_BAND} ${C}`)
  d.push(`A ${R_BAND} ${R_BAND} 0 1 0 ${C - R_BAND} ${C}`)
  d.push('Z')
  return d.join(' ')
}

function needle() {
  const [tx, ty] = NEEDLE_PARAMS.top
  const [bx, by] = NEEDLE_PARAMS.bottom
  const [dx, dy] = [tx - bx, ty - by]
  const len = Math.hypot(dx, dy)
  const [ux, uy] = [dx / len, dy / len]
  const [px, py] = [-uy, ux]
  const w = NEEDLE_PARAMS.halfWidth
  const sx = bx + ux * len * NEEDLE_PARAMS.shoulder
  const sy = by + uy * len * NEEDLE_PARAMS.shoulder
  return `M ${tx} ${ty} L ${(sx + px * w).toFixed(2)} ${(sy + py * w).toFixed(2)} ` +
         `L ${bx} ${by} L ${(sx - px * w).toFixed(2)} ${(sy - py * w).toFixed(2)} Z`
}

const GEAR = gear()
const NEEDLE = needle()

const banner = [
  '// GENERATED by scripts/generate-mark.mjs — do not edit by hand.',
  '// Adjust the parameters in that script and re-run:  node scripts/generate-mark.mjs',
].join('\n')

const out =
  `${banner}\n` +
  `export const GEAR = '${GEAR}'\n` +
  `export const NEEDLE = '${NEEDLE}'\n` +
  `export const INNER_R = ${INNER_R}\n` +
  `export const INNER_W = ${INNER_W}\n`

const __dirname = dirname(fileURLToPath(import.meta.url))
const outPath = join(__dirname, '..', 'src', 'components', 'mark-paths.generated.ts')
writeFileSync(outPath, out)
console.log(`wrote ${outPath}`)
